version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  reviewers:
  - dekz
  ignore:
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: ethereumjs-util
    versions:
    - 7.0.7
    - 7.0.8
    - 7.0.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@0x/tslint-config"
    versions:
    - 4.1.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@types/websocket"
    versions:
    - 1.0.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
