version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run:
                  name: yarn
                  command: yarn --frozen-lockfile install || yarn --frozen-lockfile install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn build
            - run: yarn scenario:all
